environment:
  OT_VERSION: 1.15rc1
  matrix:
    #- APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      #VS_GEN: Visual Studio 14 2015
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      VS_GEN: Visual Studio 15 2017

#environment:
  #OT_VERSION: 1.10
  #matrix:
    #- VS_GEN: Visual Studio 10 2010
      #VC: vc10
      #BITS: 32
      #INT_SUFFIX: ""
      #CPU_ARCH: x86
    #- VS_GEN: Visual Studio 10 2010 Win64
      #VC: vc10
      #BITS: 64
      #INT_SUFFIX: "-int32"
      #CPU_ARCH: x64
    #- VS_GEN: Visual Studio 14 2015
      #VC: vc14
      #CPU_ARCH: x86
    #- VS_GEN: Visual Studio 14 2015 Win64
      #VC: vc14
      #CPU_ARCH: x64

#version: '1.10-{build}'

install:
  - vcpkg install libxml2 openblas nlopt boost-math
  - dir -P C:\tools
  #\vcpkg\scripts\buildsystems\vcpkg.cmake

  - appveyor-retry appveyor DownloadFile https://sourceforge.net/projects/gnuwin32/files/diffutils/2.8.7-1/diffutils-2.8.7-1-bin.zip
  - 7z x diffutils-2.8.7-1-bin.zip -oC:\Libraries > nul
  - set PATH=C:\Libraries\bin;%PATH%

  # for sh, tr, cat ...
  - set PATH=C:\msys64\usr\bin;%PATH%

cache: c:\tools\vcpkg\installed\

build_script:
  - git clone https://github.com/openturns/openturns.git
  - cd openturns
  #- git checkout %OT_VERSION%
  - mkdir build && cd build
  - cmake -G"%VS_GEN%" \
      -DCMAKE_INSTALL_PREFIX=%CD:\=/%/install \
      -DCMAKE_TOOLCHAIN_FILE=c:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake \
      -DLAPACK_LIBRARIES=c:/tools/vcpkg/installed/x86-windows/lib/openblas.lib \
      -DCMAKE_SHARED_LINKER_FLAGS_RELEASE="/OPT:NOREF /INCREMENTAL:NO" \
      -DCMAKE_UNITY_BUILD=ON -DCMAKE_UNITY_BUILD_BATCH_SIZE=32 \
      -DUSE_BISON=OFF \
      -DBUILD_PYTHON=OFF \
      ..
  - cmake --build . --config Release --target install
  - cmake --build . --config Release --target tests
  - ctest -C Release --output-on-failure --timeout 100 -R cppcheck
  #- copy C:\Libraries\mingw%BITS%_dll\libgcc_s_sjlj-1.dll install\bin
  #- copy C:\Libraries\mingw%BITS%_dll\libgfortran-3.dll install\bin
  #- copy C:\Libraries\mingw%BITS%_dll\libquadmath-0.dll install\bin
  #- copy C:\Libraries\OpenBLAS-v0.2.15-Win%BITS%%INT_SUFFIX%\bin\libopenblas.dll install\bin
  #- copy C:\Libraries\tbb\bin\tbb.dll install\bin
  - 7z a -tzip %APPVEYOR_BUILD_FOLDER%\openturns-%OT_VERSION%-%VC%-%CPU_ARCH%.zip install\*

artifacts:
  - path: openturns*.zip
    name: binary

deploy:
  release: v$(appveyor_build_version)
  description: 'MSVC binaries'
  provider: GitHub
  auth_token:
    secure: 4CkqK7ssPZsVuYY4gnYun8TlaVakivCHyw+EnT6z/KdoG3iTDcebHNdHQ+cYJFt+
  artifact: binary
  draft: false
  prerelease: false
  on:
    branch: master
    #appveyor_repo_tag: true
